### ISSUE TITLE
Ok to archive?

### ISSUE THREAD

**Issue by marcoscaceres** [mikewest/credentiallessness#4]
I noticed that this is now redirecting to HTML so I'm guessing it's mission accomplished on this incubation. 

If that the case, we can set up a better redirect via the https://github.com/WICG/wicg.github.io 

And we can archive this repo (so work can just happen in over in the HTML spec). 

Would that work? or is there some reason to keep this repo around?

**Comment by yoavweiss** [comment]
@ArthurSonzogni - thoughts?

I remember we discussed this a while ago, but can't remember the conclusion..

**Comment by ArthurSonzogni** [comment]
Yes, it should be. Will do the necessary.

**Comment by ArthurSonzogni** [comment]
Okay, I understand now. I don't have access to:
https://github.com/WICG/credentiallessness/settings

@yoavweiss could you archive it please?

**Comment by yoavweiss** [comment]
OK, archiving!
